# Generated by Django 2.2.13 on 2020-12-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('updatetime', models.DateTimeField(null=True)),
                ('user', models.CharField(max_length=30)),
                ('star', models.PositiveSmallIntegerField(null=True)),
                ('short', models.TextField(null=True)),
            ],
        ),
    ]
